app/server/forms.py
from flask import Flask
from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PropertiesEdit(FlaskForm):
    edit=TextAreaField("Properties内容",validators=[DataRequired()])
    submit=SubmitField("保存")

app/server/__init__.py
from flask import Blueprint

server = Blueprint("server",__name__)

from . import views

app/server/views.py
from re import L
import flask
import sys,socket,threading,os

from flask_login import current_user, login_required
from . import server as server_blueprint
from .forms import *

class Server:
    def __init__(self,target_host,target_port,core="core",java="java") -> None:
        self.settings={"core":core,"java":java,"host":target_host,"port":target_port}
        self.is_linux=(sys.platform=="linux")
    def send(self,command:str):
        sock=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
        sock.connect((self.settings["host"],int(self.settings["port"])))
        com=command.encode(encoding="utf-8")
        sock.sendall(com)
        sock.close()
    def worker(self,directory:str,lst:str):
        os.chdir(directory)
        os.system(lst)
    def start(self):
        java=self.settings.get("java",None) or "java"
            
        j_max=self.settings.get("max",None) or ""
        j_min=self.settings.get("min",None) or ""   
        a="-Djline.terminal=jline.UnsupportedTerminal"
        b="-jar"
        try:
            name=self.settings["core"]
            #if not name.startswith('"') and not name.endswith('"'):
            #    name='"'+name+'"'
        except:
            return flask.redirect(flask.url_for("main.server"))
        path=os.path.dirname(os.path.abspath(name))+os.sep
        c="nogui"
        lst=" ".join([java,"-Xmx"+j_max,"-Xms"+j_min,a,b,name,c])
        print(lst)
        a=threading.Thread(target=self.worker,args=(path,lst))
        a.start()
        return flask.redirect(flask.url_for("main.server"))
    def _command(self,com):
        try:
            self.send(com)
        except Exception as e:
            print("error:",e)
        return flask.redirect(flask.url_for("main.server"))
    def _start(self):
        self.start()
        return flask.redirect(flask.url_for("main.server"))
    def _mset(self,key,value):
        self.settings[key]=value
        return flask.redirect(flask.url_for("main.server"))
    def _settings(self):
        return flask.jsonify(self.settings)
    def _properties(self):
        form=PropertiesEdit()
        if form.validate_on_submit():
            with open(os.path.dirname(os.path.abspath(self.settings["core"]))+os.sep+"server.properties","w+") as f: 
                f.write(form.edit.data)
            return flask.redirect(flask.url_for("server.mc_properties"))
        try:
            with open(os.path.dirname(os.path.abspath(self.settings["core"]))+os.sep+"server.properties","r+") as f: 
                form.edit.data=f.read()
        except FileNotFoundError:
            form.edit.data=""
        return flask.render_template("server/properties.html",user=current_user._get_current_object(),form=form)
c=Server(target_host="127.0.0.1",target_port="9028")
@server_blueprint.route("/command/<path:com>/")
@login_required
def mc_command(com):
    return c._command(com)
@server_blueprint.route("/start/")
@login_required
def mc_start():
    return c._start()
@server_blueprint.route("/stop/")
@login_required
def mc_stop():
    return flask.redirect(flask.url_for("server.mc_command",com="stop"))
@server_blueprint.route("/set/<key>/<path:value>/")
@login_required
def mc_set(key,value):
    return c._mset(key,value)
@server_blueprint.route("/settings/")
@login_required
def mc_settings():
    return c._settings()
@server_blueprint.route("/properties/",methods=["GET","POST"])
@login_required
def mc_properties():
    return c._properties()

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no"/>
    <meta name="renderer" content="webkit"/>
    <meta name="force-rendering" content="webkit"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <!--MDUI CSS-->
    <link rel="stylesheet" href="{{ url_for("static",filename="css/mdui.min.css") }}"><link rel="stylesheet" href="https://cdn.w3cbus.com/mdui/docs~1/static/index.0132e177.css">
    <title>{% block title %}{% endblock %} -Aurora Core</title>    
</head>
<!--Header-->
<header class="appbar mdui-appbar mdui-appbar-fixed">
    <div class="mdui-toolbar mdui-color-theme">
        <div class="mdui-typo-headline mdui-hidden-xs">Aurora Web</div><div class="mdui-typo-title">{% block pagename %}{% endblock %}</div>
        <div class="mdui-toolbar-spacer"></div>
        <a href="{{ url_for('auth.logout') }}">登出</a>
    </div>
    
</header>
<body class="mdui-drawer-body-left mdui-appbar-with-toolbar mdui-theme-primary-cyan mdui-theme-layout-auto mdui-loaded" background="{{ config["BACKGROUND_URI"] }}" >
    <div align="center">
    <!--Base Template-->
    {% block body %}
    {% endblock %}
    </div>
    <!--MDUI JavaScript-->
    <script src="{{ url_for("static",filename="js/mdui.min.js") }}"></script><script src="https://cdn.w3cbus.com/mdui/docs~1/static/index.95ae2041.js"></script>
</body>
</html>

app/templates/drawer.html
{% extends "base.html" %}
{% macro drawer_item(content,href) %}
    <div class="mdui-list-item mdui-ripple"><h3><a href="{{ href }}">{{ content }}</a></h3></div>
{% endmacro %}
{% macro drawer_item_admin(content,href,user) %}
    {% if user.username.startswith("!") %}
    {{ drawer_item(content,href) }}
    {% endif %}
{% endmacro %}
{% block body %}
<div class="mdui-drawer mdui-drawer-open mdui-color-cyan-600">
    <div class="mdui-list" mdui-collapse="{accordion: true}" style="margin-bottom: 76px;">
        {{ drawer_item("面板","/") }}
        {{ drawer_item("服务器","/server/") }}
        <div class="mdui-divider"></div>
        {% block items %}
        {% endblock %}
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends "drawer.html" %}
{% import "drawer.html" as drawer %}
{% block title %}主页{% endblock %}
{% block pagename %}主页{% endblock %}
{% block body %} 
{{ super() }}
<div class="mdui-row">
    <div class="mdui-col-sm-6 mdui-col-md-10">
    <div class="mdui-card" style="background-color: rgba(255, 255, 255, 0.5)">
        <div class="mdui-card-primary">
            <div class="mdui-card-primary-title"><font style="size:20mm;">主页</font></div>
          </div>
    <div class="mdui-card-content">
    
    {% if user.username.startswith("!") %}
    <div class="mdui-row">
        <div class="mdui-col-sm-6 mdui-col-md-10">
        <div class="mdui-card" style="background-color: rgba(255, 255, 255, 0.5)">
            <div class="mdui-card-primary">
                <div class="mdui-card-primary-title"><font style="size:20mm;">内存</font></div>
              </div>
              <div class="mdui-card-content">
            <h2>总内存：{{ mems[0] }}MB</h2>
            <h2>已使用内存：{{ mems[1] }}MB</h2>
            <h2>可用内存：{{ mems[2] }}MB</h2>
        </div>
    </div>
    </div>
    </div>
    {% endif %}
    
    </div>
    </div>
    </div>
    </div>
{% endblock %}
{% block items %}
    {{ drawer.drawer_item_admin("用户","/user/",user) }}
{% endblock %}

app/templates/server.html
{% extends "drawer.html" %}
{% import "drawer.html" as drawer %}
{% block title %}服务器{% endblock %}
{% block pagename %}服务器{% endblock %}
{% block body %} 
{{ super() }}
<div class="mdui-row">
    <div class="mdui-col-sm-6 mdui-col-md-10">
    <div class="mdui-card" style="background-color: rgba(255, 255, 255, 0.5)">
        <div class="mdui-card-primary">
            <div class="mdui-card-primary-title"><font style="size:20mm;">服务器</font></div>
          </div>
    <div class="mdui-card-content">
        <div class="mdui-row">
            <div class="mdui-col-sm-6 mdui-col-md-10">
            <div class="mdui-card" style="background-color: rgba(255, 255, 255, 0.5)">
                <div class="mdui-card-primary">
                    <div class="mdui-card-primary-title"><font style="size:20mm;">服务器操作</font></div>
                  </div>
            <div class="mdui-card-content">
                <!--服务器操作-->
                <a href={{ url_for("server.mc_start") }}><button class="mdui-btn mdui-btn-raised"><font color="grey">启动服务器</font></button></a>
                <a href={{ url_for("server.mc_stop") }}><button class="mdui-btn mdui-btn-raised"><font color="grey">停止服务器</font></button></a>
                <form method="post">
                    {{ command_form.hidden_tag() }}
                    <div class="mdui-textfield">{{ command_form.command(class="mdui-textfield-input",placeholder="指令") }}</div>
                    {{ command_form.submit(class="mdui-btn mdui-btn-raised") }}
                </form>
            </div>
            </div>
            </div>
            </div>
            <div class="mdui-row">
                <div class="mdui-col-sm-6 mdui-col-md-10">
                <div class="mdui-card" style="background-color: rgba(255, 255, 255, 0.5)">
                    <div class="mdui-card-primary">
                        <div class="mdui-card-primary-title"><font style="size:20mm;">服务器配置</font></div>
                      </div>
                <div class="mdui-card-content">
                    <!--服务器配置-->
                    <form method="post">
                        {{ settings_form.hidden_tag() }}
                        <div class="mdui-textfield">
                            <font size="4">键</font>
                        {{ settings_form.key(class="mdui-textfield-input mdui-text-right",style="width:1000px;display:inline;",placeholder="键") }}
                        </div>
                        <div class="mdui-textfield">
                            <font size="4">值</font>
                        {{ settings_form.value(class="mdui-textfield-input mdui-text-right",style="width:1000px;display:inline;",placeholder="值") }}
                        </div>
                        {{ settings_form.submit(class="mdui-btn mdui-btn-raised") }}
                    </form>
                </div>
                </div>
                </div>
                </div>
                <div class="mdui-row">
                    <div class="mdui-col-sm-6 mdui-col-md-10">
                    <div class="mdui-card" style="background-color: rgba(255, 255, 255, 0.5)">
                        <div class="mdui-card-primary">
                            <div class="mdui-card-primary-title"><font style="size:20mm;">服务器Properties</font></div>
                          </div>
                    <div class="mdui-card-content">
                        <!--服务器Properties-->
                        <a href="{{ url_for("server.mc_properties") }}"><button class="mdui-btn mdui-btn-raised"><font color="grey">编辑</font></button></a>
                    </div>
                    </div>
                    </div>
                    </div>
                    <div class="mdui-row">
                        <div class="mdui-col-sm-6 mdui-col-md-10">
                        <div class="mdui-card" style="background-color: rgba(255, 255, 255, 0.5)">
                            <div class="mdui-card-primary">
                                <div class="mdui-card-primary-title"><font style="size:20mm;">小贴士</font></div>
                              </div>
                        <div class="mdui-card-content">
                            <!--Tips-->
                            <ul class="mdui-list">
                                    <li class="mdui-list-item"><h3>服务器需要设置才能启动，试试服务器配置一栏：</h3></li>
                                    <li class="mdui-list-item">java : java 路径 (环境有配置的话直接java就行)</li>
                                        <li class="mdui-list-item">core : 服务端核心路径</li>
                                            <li class="mdui-list-item">max  : 最大堆内存</li>
                                                <li class="mdui-list-item"> min  : 初始堆内存</li>
                                                    <li class="mdui-list-item"> host : 服务器地址</li>
                                                        <li class="mdui-list-item">port : Aurora Core 使用的端口号(默认为9028)</li>
                            </ul>
                        </div>
                        </div>
                        </div>
                        </div>
    </div>
    </div>
    </div>
    </div>
{% endblock %}
{% block items %}
    {{ drawer.drawer_item_admin("用户","/user/",user) }}
{% endblock %}

app/templates/user.html
{% extends "drawer.html" %}
{% import "drawer.html" as drawer %}
{% block title %}用户{% endblock %}
{% block pagename %}用户{% endblock %}
{% block body %} 
{{ super() }}
<div class="mdui-row">
    <div class="mdui-col-sm-6 mdui-col-md-10">
    <div class="mdui-card" style="background-color: rgba(255, 255, 255, 0.5)">
        <div class="mdui-card-primary">
            <div class="mdui-card-primary-title">用户管理</div>
            <a href="{{ url_for("main.new_user") }}"><button class="mdui-btn mdui-btn-raised"><font color="grey">新建用户</font></button></a>
            <div><span class="mdui-color-red">
                {% if error=="1" %}
                用户名或密码错误！
                {% elif error=="2" %}
                用户名重复！
                {% endif %}
            </span></div>
          </div>
    <div class="mdui-card-content">
        <ul class="mdui-list">
        {% for user in users %}
        <div class="mdui-divider"></div>
            <li class="mdui-list-item mdui-ripple mdui-list-dense">
                {% if user.username.startswith("!") %}
                <h4><font color="red">[管理员]&nbsp&nbsp&nbsp</font></h4>
                {% endif %}
                <div align="left" style="font-size:large;font-weight:900;">{{ user.username }}</div>
                <div class="mdui-toolbar-spacer"></div>
                <div><a href={{ url_for("main.user_detail",username=user.username) }}><button class="mdui-btn mdui-btn-raised mdui-color-cyan-100">用户信息</button></a></div>
                <span style="margin-left: 8px;"> | </span>
                <div><a href={{ url_for("main.delete",name=user.username) }}><button class="mdui-btn mdui-btn-raised mdui-color-red-100">删除用户</button></a></div>
            </li>
    {% endfor %}
    </ul>
    <div class="mdui-divider"></div>
    </div>
    </div>
    </div>
    </div>
{% endblock %}
{% block items %}
    {{ drawer.drawer_item("用户","/user/") }}
{% endblock %}

app/templates/user_delete.html
{% extends "drawer.html" %}
{% import "drawer.html" as drawer %}
{% block title %}删除用户{% endblock %}
{% block pagename %}删除用户{% endblock %}
{% block body %} 
{{ super() }}
<div class="mdui-row">
    <div class="mdui-col-sm-6 mdui-col-md-10">
    <div class="mdui-card" style="background-color: rgba(255, 255, 255, 0.5)">
        <div class="mdui-card-primary">
            <div class="mdui-card-primary-title"><font style="size:20mm;">用户删除</font></div>
          </div>
    <div class="mdui-card-content">
        <h1>你确定要删除吗？</h1>
        <h2>在下面输入用户名来确认删除。</h2>
        <h3>错误将跳转至用户管理。</h3>
        <form method="post">
            {{ form.hidden_tag() }}
            {{ form.repeat(class="mdui-textfield-input mdui-text-right",style="width:600px;display:inline;",placeholder="重复用户名") }}
            {{ form.submit(class="mdui-btn mdui-btn-raised") }}
        </form>
    </div>
    </div>
    </div>
    </div>
{% endblock %}
{% block items %}
{{ drawer.drawer_item("用户","/user/") }}
{% endblock %}

app/templates/user_detail.html
{% extends "drawer.html" %}
{% import "drawer.html" as drawer %}
{% block title %}用户Profile{% endblock %}
{% block pagename %}用户Profile{% endblock %}
{% block body %} 
{{ super() }}
<div class="mdui-row">
    <div class="mdui-col-sm-6 mdui-col-md-10">
    <div class="mdui-card" style="background-color: rgba(255, 255, 255, 0.5)">
        <div class="mdui-card-primary">
            <div class="mdui-card-primary-title"><font style="size:20mm;">{{ user.username|upper }}</font></div>
          </div>
    <div class="mdui-card-content">
        <form method="post">
            {{ form.hidden_tag() }}
        <ul class="mdui-list">
            <li class="mdui-list-item">
                <font size="4">权限</font>
            <div class="mdui-toolbar-spacer"></div>
            {% if user.username.startswith("!") %}
                <h4><font color="red" size="4">管理员</font></h4>
            {% else %}
            <h4><font size="4">普通用户</font></h4>
            {% endif %}
            </li>
            <li>                
                <div class="mdui-textfield">
                    <font size="4">密码</font>
                    {{ form.password(class="mdui-textfield-input mdui-text-right",style="width:1300px;display:inline;",type="password",placeholder="密码") }}    
                  </div>
                
            </li>
        </ul>
        {{ form.submit(class="mdui-btn mdui-btn-raised") }}
    </form>
    </div>
    </div>
    </div>
    </div>
{% endblock %}
{% block items %}
{{ drawer.drawer_item("用户","/user/") }}
{% endblock %}

app/templates/user_new.html
{% extends "drawer.html" %}
{% import "drawer.html" as drawer %}
{% block title %}新建用户{% endblock %}
{% block pagename %}新建用户{% endblock %}
{% block body %} 
{{ super() }}
<div class="mdui-row">
    <div class="mdui-col-sm-6 mdui-col-md-10">
    <div class="mdui-card" style="background-color: rgba(255, 255, 255, 0.5)">
        <div class="mdui-card-primary">
            <div class="mdui-card-primary-title"><font style="size:20mm;">新建用户</font></div>
          </div>
    <div class="mdui-card-content">
        <form method="post">
            {{ form.hidden_tag() }}
        <ul class="mdui-list">
            <li class="mdui-list-item">
                <div class="mdui-textfield">
                    <font size="4">用户名</font>
                    {{ form.username(class="mdui-textfield-input mdui-text-right",style="width:1000px;display:inline;",placeholder="用户名") }}    
                  </div>
            </li>
            <li class="mdui-list-item">                
                <div class="mdui-textfield">
                    <font size="4">密码</font>
                    {{ form.password(class="mdui-textfield-input mdui-text-right",style="width:1000px;display:inline;",type="password",placeholder="密码") }}    
                  </div>
                
            </li>
        </ul>
        {{ form.submit(class="mdui-btn mdui-btn-raised") }}
    </form>
    </div>
    </div>
    </div>
    </div>
{% endblock %}
{% block items %}
{{ drawer.drawer_item("用户","/user/") }}
{% endblock %}